[log]
level = "info"

[server]
domain = "localhost"
schema = "http"
ip = "0.0.0.0"
port = "3000"

[database]
schema = "postgres"
host = "127.0.0.1"
port = "5432"
name = "aver"
user = "aver"
pass = "aver"

[session]
schema = "redis"
host = "127.0.0.1"
port = "6379"

[ocm]

[ocm.provider]
enable = true
prefix = "ocm"
endpoint = "http://localhost:3000"
provider = "Aver (Reva but backwards)"

[ocm.provider.capabilities]
mfa_capable = true
notifications = true
invite_accepted = true

[[ocm.provider.resource_types]]
name = "file"

[ocm.provider.resource_types.share_types]
user = true
group = true
federation = true

[ocm.provider.resource_types.protocols]
webdav = "/dav"
webapp = "/app"
datatx = "/dav"
