//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod organizations;
pub mod permissions;
pub mod role_permissions;
pub mod roles;
pub mod user_organization_roles;
pub mod users;
