//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::ocm_contacts::Entity as OcmContacts;
pub use super::ocm_invite_tokens::Entity as OcmInviteTokens;
pub use super::ocm_users::Entity as OcmUsers;
pub use super::organizations::Entity as Organizations;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::user_org_roles::Entity as UserOrgRoles;
pub use super::users::Entity as Users;
