//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::organizations::Entity as Organizations;
pub use super::permissions::Entity as Permissions;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::user_organization_roles::Entity as UserOrganizationRoles;
pub use super::users::Entity as Users;
