[package]
name = "aver"
version = "0.1.0"

rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
dotenvy = "0.15.7"
serde_json = "1.0.122"
tracing = "0.1.40"
once_cell = "1.19.0"


[dependencies.config]
version = "0.14.0"
features = [
    "toml",
]

[dependencies.mimalloc]
version = "0.1.43"
features = [
    "secure"
]

[dependencies.poem]
version = "3.0.4"
features = [
]

[dependencies.reqwest]
version = "0.12.5"
features = [
    "json",
    "rustls-tls",
]

[dependencies.serde]
version = "1.0.204"
features = [
    "derive",
]

[dependencies.tokio]
version = "1.39.2"
features = [
    "macros",
    "rt-multi-thread",
    "time",
]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = [
    "env-filter",
]